### ISSUE TITLE
can't get it to work

### ISSUE THREAD

**Issue by jain7th** [FireNeslo/gulp-audiosprite-pkg#1]
Hi there,
I tried to use this plugin but it just returns errors.

First I replaced `var audio = require('../index')` with `audio = require('gulp-audiosprite-pkg')` but I just get
`[17:26:09] Starting 'audio'...
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
  at Object.exports._errnoException (util.js:856:11)
  at exports._exceptionWithHostPort (util.js:879:20)
  at WriteWrap.afterWrite (net.js:763:14)`

the task looks like this:
`gulp.task('audio', function () {
return gulp.src("sounds/**/*.aif")
    .pipe(audio('multi.{mp3,ogg}'))
    .pipe(gulp.dest('build/audio'));
});`

(the location should be correct since I previously was able to convert the aiff to mp3 with gulp-fluent-ffmpeg from there)

**Comment by FireNeslo** [comment]
Hmm interesting. do you have any audio samples i could use or a code snipped i could use to try to recreate your issue?

**Comment by FireNeslo** [comment]
This worked for me given that you meant to write aiff.

``` js
var gulp = require('gulp')
var audio = require('gulp-audiosprite-pkg')

gulp.task('default', function () {
  return gulp.src("sounds/**/*.aiff")
    .pipe(audio('multi.{mp3,ogg}'))
    .pipe(gulp.dest('build/audio'));
});
```

**Comment by jain7th** [comment]
Hm, I don't think I'm allowed to share the files right now (but I'll check up on that later) :/
*.aif  was correct since that's the extension the sounddesigner chose and they work correctly when I play them with vlc and finder quicklook.
I tried changing the extension but the problem remained.

The weird thing is, according to the json the files are being recognised and the lengths get read. But the resulting audio just has the first second or so of the first clip. And the console spits out the same error as before.
